### PR TITLE
Added __DIR__ to imports and / to hrefs.

### PR DESCRIPTION
**Pull request by lostcarpark**
This change is to allow paths to include subdirectories.

To facilitate this, __DIR__ has been added to imports/requires in utility files, so that they can be safely included from files in subdirectories.

Menu links have "/" added to their paths so that the will be relative to the site root.

The ultimate aim of this is to allow modules to be placed in a largely self contained directory under the /module directory. However, it could be useful to move other parts of the site into directories. For example, moving all Staff pages into a /staff directory could help make the project easier to navigate.

### CODE REVIEW

**Comment by bcholmes** [comment]
I think this makes sense. I had previously wondered if there was a case where the app was deployed in a location like:

https://www.example.com/mycon2024/login.php

That doesn't quite fit the pattern you're using. Thoughts?

**Comment by lostcarpark** [comment]
That is a problem I had not considered. Would having a config `define` setting for the base path of the site on the webserver be a better solution?

**Comment by bcholmes** [comment]
Yeah, a config setting would probably work.

**Comment by lostcarpark** [comment]
I have added a `BASE_PATH` setting to `db_name_sample.php`, defaulting to '/'. This can be set to the path containing PlanZ on the webserver.

**Comment by lostcarpark** [comment]
I found a couple of issues I missed with the up and down arrows in the header and the favicon. Hopefully fixed now.

I've done some testing with the site in a subdirectory, and it seemed to work well.

**Pull request merged**
