### PR TITLE
First stab at a standards doc for databse entities.

### PR DESCRIPTION
**Pull request by lostcarpark**
I want to suggest naming standards for DB objects.

This is a starting point for discussion, so feel free to add or change, or if you have different preference please specify. I'm not too particular on what the standard should be, just that we agree one and follow it consistently.

I also think that now would be a good time to start a refactoring effort, before PlanZ is in use by a lot of conventions.

### CODE REVIEW

**Comment by lostcarpark** [comment]
Oh, just noticed @LVerhulst4321 suggested calling the folder `Documentation`. Would you like me to rename it?

**Comment by LVerhulst4321** [comment]
Yes, please rename the folder to Documentation. I like full names usually.
I'm still reading your doc. It's also middle of my work day, so that's taking priority. :-)
So far, I'm liking the doc.

**Comment by lostcarpark** [comment]
Fionna has corrected my typos. :-)

**Comment by LVerhulst4321** [comment]
I'm kind of torn about the table names as there are a LOT of existing tables that are plural and so would not match the standard. On the other hand, the new standard would make it easier to distinguish the new stuff from the old stuff. So, let's go for it. And slowly start changing things over as needed (and if needed).

**Pull request merged**
