### PR TITLE
Address Issue #82 : retool the Brainstorm function to remove WisCon-specific references

### PR DESCRIPTION
**Pull request by bcholmes**
I've revised the Brainstorm function, bringing the React code into our main React app. This has the effect of making the Brainstorm tool into something that is no longer a stand-alone app. Thus, the header, favicon, footer, and menubar are all managed in the typeical PlanZ way.

That changes the look and feel, but not too dramatically. Nonetheless, the end result is a bit more unified with the rest of the application.

Screen Shot 2022-09-24 at 2 07 40 PM

The sidebar text is fetched from the CustomText table; I've populated this with a default message.

### CODE REVIEW

**Comment by lostcarpark** [comment]
Looks good overall.
The previous "Suggest a session" page looked neat, but lacked consistency.
I'm not sure how to build the new version, as there isn't a "build" script in package.json.
I thought there were some instructions on setting up the React client, but they don't appear to be in the repo.
At a minimum we need:
1. Instructions to build the react app.
2. Tables that need to be populated to use Brainstorming.

**Comment by bcholmes** [comment]
>     1. Instructions to build the react app.

The instructions to build the React app are in clients/README.md . I'll look at the table population.

**Comment by lostcarpark** [comment]
Ah thanks. I'll try that today. Not sure how I missed it.
I think a reference in the main readme to help locate it would a good idea.

**Comment by lostcarpark** [comment]
Does the composer command still need to be run?

**Comment by bcholmes** [comment]
The composer command is no longer needed.

**Comment by lostcarpark** [comment]
A couple of thoughts, without having tried it yet...
1. At some point it would be nice to make the React part run in a React development server for faster development (though obviously still build for production).
2. I would love to move some of the Composer dependences out of the repo, and have a Composer update load them. In theory it should even be possible for the whole PlanZ project to be loaded with Composer instead of git.

**Comment by bcholmes** [comment]
>     1. At some point it would be nice to make the React part run in a React development server for faster development (though obviously still build for production).

Yeah. The original brainstorm code could run as a development server. The consequence of that package.json configuration was that, when built, we ended up creating a JavaScript file with a hashcode appended to the JS name, which meant that I couldn't just reference the JS at a well-known name. I'm sure there's a way to fix that; I just lack the webpack knowledge to know how to do that.

**Comment by bcholmes** [comment]
I've added some additional table set-up documentation in ed4014fb7e80eb5bb8d06631949408e4e47ed884

**Pull request merged**
