### PR TITLE
Fix query

### PR DESCRIPTION
**Pull request by LVerhulst4321**
Fixed queries that were giving off sql errors.

### CODE REVIEW

**Comment by bcholmes** [comment]
That's weird. I know that I've used rank without backticks for things. Maybe you've got a slightly different configuration of your MySQL instance.

**Comment by lostcarpark** [comment]
Backticks aren't needed if you have a table name or alias prefix.

In this case an alternative would have been to use `Rooms.function`.

**Comment by LVerhulst4321** [comment]
Yeah, I think the backticks are because of the version of MySQL that I'm using. Should I leave the backticks, or update like James suggested with Rooms.function? I actually want to change the field name so that it isn't using an MySQL reserved word, but that's a different project. And same with the rank field name in the other table.

**Comment by lostcarpark** [comment]
I believe either solution is acceptable. I don't think there's any advantage to switching approach. I think the best long term solution is to refactor the table.

I'm pretty sure both approaches work with any reasonably modern version o f MySQL or MariaDB. Both `function` and `rank` became reserved words with MySQL 8, which was released in 2018 (TBH I thought functions were supported quite a bit earlier).

**Pull request merged**
