### PR TITLE
- add some look and feel improvements

### PR DESCRIPTION
**Pull request by bcholmes**
This is a first-pass at a look-and-feel revision for Plan Z. Mostly it's just about removing the ugly gradients.

Screen Shot 2022-03-20 at 12 03 25 PM

Screen Shot 2022-03-20 at 12 04 10 PM

The logo was designed by a designer I've used before , [Keith Curtis](http://kacurtis.com/), who I engaged with the understanding that this logo will be included as part of an open source license. I'll probably get a newer version, with some tweaks and a refreshed favicon in the next day or so.

### CODE REVIEW

**Comment by lostcarpark** [comment]
Ooh! I like the new logo!

**Comment by lostcarpark** [comment]
Out of interest, is the logo created in a vector art program? If so, could it be included in SVG format so it could be resized losslessly?

**Comment by bcholmes** [comment]
I'm almost-certain that it was created in a vector art program. I'll talk to Keith about getting a vector version of it (I'm just waiting on some final deliverables from him).

**Comment by LVerhulst4321** [comment]
I like it! Nice logo! I've reviewed the changed files. Looks good to me. Feel free to do the Merge step. :-)

**Pull request merged**
